@startuml
!theme plain

actor Client
actor Employee
participant "POS System" as POS
participant "Backend Server" as Server

title Client seating(no seating available)

/'== Arrival =='/
Client -> Employee: Enters the restaurant/bar
Employee -> Client: Greets the Client

/'== Check Seating Availability =='/
Employee -> POS: Request available seating options
POS -> Server: Retrieve seating availability
Server --> POS: Return available seating options
POS --> Employee: Display no available seating options 

/'== Inform the client =='/
Employee -> Client: Inform no seating available

@enduml
