export {
  discountKeys,
  useDiscounts,
  useCreateDiscount,
  useUpdateDiscount,
  useDeleteDiscount,
  useApplicableOrderDiscount,
  useApplicableServiceDiscount,
  useServiceDiscounts,
  useCreateServiceDiscount,
  useUpdateServiceDiscount,
  useMenuDiscounts,
  useCreateMenuDiscount,
  useUpdateMenuDiscount,
} from "./discount-hooks";
