
@startuml
!theme plain

actor Client
actor Employee
participant "POS System" as POS
participant "Backend Server" as Server

title Client seating(available)

/'== Arrival =='/
Client -> Employee: Enters the restaurant/bar
Employee -> Client: Greets the Client

/'== Check Seating Availability =='/
Employee -> POS: Request available seating options
POS -> Server: Retrieve seating availability
Server --> POS: Return available seating options
POS --> Employee: Display available seating options

/'== Assign seat =='/
Employee -> Client: Suggest available seating options
Client -> Employee: Chooses seating option
Employee -> POS: Assign Client to table
POS -> Server: Save and validate table assignment

alt Validation Success
    Server --> POS: Confirm table assignment saved
    POS --> Employee: Confirm table assignment
    Employee -> Client: Guide to assigned table
else Validation Failure
    Server --> POS: Table assignment failed
    POS --> Employee: Notify assignment failure
    Employee -> Client: Inform table unavailable\nSuggest alternative or to wait
end

@enduml

