@startuml
|Owner|
start
:Log in to UniServe;
:Navigate to **Business → Specific Business**;
:Select **Manage Employees**;
:Choose action;
fork
  -[Invite Employee]
  :Open "Invite Employee" form;
  :Fill Email;
  :Select Job for the employee;
  :Choose Employee work hours;
  :Fill in expiration of invite;
  :Choose Employee work location;
  :Press "Generate and Send Code";
  :Receive confirmation toast (success / error);
fork again
  -[Manage Existing Employee]
  :Search for employee;
  :Select "Manage";
  :View profile (salary, status, role);
  :Make modifications;
  :Confirm changes;
  :Receive confirmation toast (success / error);
end fork

stop
@enduml
